//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntikaMarketim.Models
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Cart
    {
        public int Id { get; set; }
        public int Count { get; set; }
        public decimal UnitPrice { get; set; }
        public short Discount { get; set; }
        public string UserKey { get; set; }
        public int ProductId { get; set; }
        public bool OrderCompleted { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
